# Generated by Django 2.2.14 on 2020-09-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Publishing Date')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-publishing_date', 'id'],
            },
        ),
    ]
